-- Remap questions to correct topics (add M2M entries)
-- Generated by remap-topics.mjs

-- DUPLICATE: pannelli_posteriori_per_autoveicoli_adibiti_al_trasporto_di_cose_di_massa_a_pieno_carico gets same questions as pannelli_posteriori_trasporto_cose
INSERT INTO question_topics (question_id, topic_id)
SELECT qt.question_id, t_new.id
FROM question_topics qt
JOIN topics t_old ON t_old.id = qt.topic_id AND t_old.topic_key = 'pannelli_posteriori_trasporto_cose'
CROSS JOIN topics t_new
WHERE t_new.topic_key = 'pannelli_posteriori_per_autoveicoli_adibiti_al_trasporto_di_cose_di_massa_a_pieno_carico'
ON CONFLICT DO NOTHING;

-- DUPLICATE: sporto_cose_di_massa_a_pieno_carico gets same questions as pannelli_posteriori_trasporto_cose
INSERT INTO question_topics (question_id, topic_id)
SELECT qt.question_id, t_new.id
FROM question_topics qt
JOIN topics t_old ON t_old.id = qt.topic_id AND t_old.topic_key = 'pannelli_posteriori_trasporto_cose'
CROSS JOIN topics t_new
WHERE t_new.topic_key = 'sporto_cose_di_massa_a_pieno_carico'
ON CONFLICT DO NOTHING;

-- DUPLICATE: in_un_incidente_chi_e_civilmente_obbligato_a_risarcire_i_danni gets same questions as incidente_chi_civilmente_obbligato_risarcire
INSERT INTO question_topics (question_id, topic_id)
SELECT qt.question_id, t_new.id
FROM question_topics qt
JOIN topics t_old ON t_old.id = qt.topic_id AND t_old.topic_key = 'incidente_chi_civilmente_obbligato_risarcire'
CROSS JOIN topics t_new
WHERE t_new.topic_key = 'in_un_incidente_chi_e_civilmente_obbligato_a_risarcire_i_danni'
ON CONFLICT DO NOTHING;

-- DUPLICATE: se_si_stanno_seguendo_terapie_cure_con_farmaci_ad_azione_sedativa gets same questions as terapie_farmaci_sedativi
INSERT INTO question_topics (question_id, topic_id)
SELECT qt.question_id, t_new.id
FROM question_topics qt
JOIN topics t_old ON t_old.id = qt.topic_id AND t_old.topic_key = 'terapie_farmaci_sedativi'
CROSS JOIN topics t_new
WHERE t_new.topic_key = 'se_si_stanno_seguendo_terapie_cure_con_farmaci_ad_azione_sedativa'
ON CONFLICT DO NOTHING;

-- DUPLICATE: il_mancato_senso_del_pericolo_durante_la_guida_puo_essere_dato gets same questions as mancato_senso_del_pericolo_durante
INSERT INTO question_topics (question_id, topic_id)
SELECT qt.question_id, t_new.id
FROM question_topics qt
JOIN topics t_old ON t_old.id = qt.topic_id AND t_old.topic_key = 'mancato_senso_del_pericolo_durante'
CROSS JOIN topics t_new
WHERE t_new.topic_key = 'il_mancato_senso_del_pericolo_durante_la_guida_puo_essere_dato'
ON CONFLICT DO NOTHING;

-- DUPLICATE: preavviso_di_deviazione_obbligatoria_per_autocarri_in_transito gets same questions as preavviso_deviazione_autocarri
INSERT INTO question_topics (question_id, topic_id)
SELECT qt.question_id, t_new.id
FROM question_topics qt
JOIN topics t_old ON t_old.id = qt.topic_id AND t_old.topic_key = 'preavviso_deviazione_autocarri'
CROSS JOIN topics t_new
WHERE t_new.topic_key = 'preavviso_di_deviazione_obbligatoria_per_autocarri_in_transito'
ON CONFLICT DO NOTHING;

-- TEXT MATCH: fermarsi_e_dare (18 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'fermarsi_e_dare'
AND q.code IN ('A001', 'B18775', 'B20442', 'B20526', 'B20627', 'B20900', 'B22119', 'QB00071', 'QB00072', 'QB00076', 'QB00078', 'QB00085', 'QB00086', 'QB00095', 'QB00097', 'QB00103', 'QB00165', 'QB00245')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: preavviso_di_fermarsi_e_dare (3 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'preavviso_di_fermarsi_e_dare'
AND q.code IN ('B20516', 'B20522', 'QB00069')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: metri (6 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'metri'
AND q.code IN ('B19580', 'B19582', 'B19586', 'B19587', 'B19589', 'B22551')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: quando_il_semaforo_emette_luce_verde_nella_nostra (1 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'quando_il_semaforo_emette_luce_verde_nella_nostra'
AND q.code IN ('B21167')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: possiamo_trovare_una_luce_gialla_lampeggiante (24 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'possiamo_trovare_una_luce_gialla_lampeggiante'
AND q.code IN ('B18809', 'B19408', 'B19500', 'B20484', 'B20577', 'B20704', 'B21009', 'B21013', 'B21016', 'B21037', 'B21060', 'B21082', 'B21127', 'B21128', 'B21129', 'B21131', 'B21132', 'B21134', 'B21993', 'B22472', 'B22887', 'B22909', 'QB00119', 'QB00120')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: in_una_strada_a_senso_unico_con_la_striscia_bianca_discontinua (6 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'in_una_strada_a_senso_unico_con_la_striscia_bianca_discontinua'
AND q.code IN ('B20776', 'B20905', 'B20906', 'B20907', 'B20909', 'B20910')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: simbolo_del_tergicristallo_e (3 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'simbolo_del_tergicristallo_e'
AND q.code IN ('B24278', 'B24711', 'B25292')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: lavacristallo_e (1 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'lavacristallo_e'
AND q.code IN ('B25293')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: olio_e (11 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'olio_e'
AND q.code IN ('B24189', 'B24280', 'B24281', 'B24282', 'B24293', 'B24294', 'B24297', 'B24298', 'B24299', 'B24300', 'B24774')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: simbolo_del_lunotto_termico (1 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'simbolo_del_lunotto_termico'
AND q.code IN ('B25065')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: pannelli_arancioni_per_trasporto_merci_pericolose (2 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'pannelli_arancioni_per_trasporto_merci_pericolose'
AND q.code IN ('B23946', 'B23949')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: cause_principali_di_incidenti_possono (1 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'cause_principali_di_incidenti_possono'
AND q.code IN ('B31030')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: uscita_delle_gallerie_e (7 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'uscita_delle_gallerie_e'
AND q.code IN ('B18891', 'B19229', 'B19431', 'B19454', 'B21649', 'B21980', 'B21987')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: si_sbaglia_corsia (11 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'si_sbaglia_corsia'
AND q.code IN ('B22716', 'B22717', 'B22718', 'B22719', 'B22720', 'B22723', 'B22724', 'B22725', 'B22726', 'B22727', 'B22728')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: responsabilita_civile_auto_i (29 questions - RCA assicurazione)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'responsabilita_civile_auto_i'
AND q.code IN ('B25021', 'B25022', 'B25023', 'B25024', 'B25025', 'B25026', 'B25162', 'B25197', 'B25289', 'B25358', 'QB00423', 'QB00424', 'QB00431', 'QB00433', 'QB00434', 'QB00435', 'QB00436', 'QB00437', 'QB00438', 'QB00439', 'QB00440', 'QB00441', 'QB00442', 'QB00443', 'QB00444', 'QB00445', 'QB00446', 'QB00447', 'QB00448')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: influenza_di_sostanze_stupefacenti_e (3 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'influenza_di_sostanze_stupefacenti_e'
AND q.code IN ('QB00375', 'QB00376', 'QB00381')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: inquinamento_atmosferico_prodotto_dai_veicoli_con_motore_diesel (1 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'inquinamento_atmosferico_prodotto_dai_veicoli_con_motore_diesel'
AND q.code IN ('B25132')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: cono (1 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'cono'
AND q.code IN ('B23927')
ON CONFLICT DO NOTHING;

-- TEXT MATCH: delineatori_per_gallerie_a_senso_unico (2 questions)
INSERT INTO question_topics (question_id, topic_id)
SELECT q.id, t.id
FROM questions q
CROSS JOIN topics t
WHERE t.topic_key = 'delineatori_per_gallerie_a_senso_unico'
AND q.code IN ('B21940', 'B21941')
ON CONFLICT DO NOTHING;
